name: Publish to W3C
on:
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate, and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Publish as W3C Technical Report Snapshot
        uses: w3c/spec-prod@v2
        if: ${{ github.ref_name == 'main' }}
        with:
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN }}
          W3C_WG_DECISION_URL: https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-08-03-vcwg#resolution1
          W3C_BUILD_OVERRIDE: |
             shortName: vc-data-model-2.0
             specStatus: WD
